sudo: false
language: ruby
rvm:
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
install: bundle install --jobs=3 --retry=3
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bin/update; fi
  - bundle exec rake spec
